force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>Deal_Id__c</fullName>
    <externalId>true</externalId>
    <label>Deal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/PMP_Type__c.field-meta.xml
<CustomField>
    <fullName>PMP_Type__c</fullName>
    <label>PMP Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Programmatic_Revenue_Landing__c.field-meta.xml
<CustomField>
    <fullName>Programmatic_Revenue_Landing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programmatic Revenue Landing</label>
    <referenceTo>Programmatic_Revenue_Landing__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Booking_Amount__c</fullName>
    <label>Original Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/Programmatic_Revenue_Landing__c.object-meta.xml
<CustomObject>
    <label>Programmatic Revenue Landing</label>
    <nameField>
        <label>Programmatic Revenue Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programmatic Revenue Landing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <externalId>true</externalId>
    <label>Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Programmatic Guaranteed</fullName>
            </value>
            <value>
                <fullName>Programmatic PMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Deal_Type_Formula__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type_Formula__c</fullName>
    <formula>IF( TEXT( Deal_Type__c )=&apos;programmatic_guarantee&apos;,&apos;Programmatic Guaranteed&apos;,&apos;Programmatic PMP&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Type Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Demand_Partner__c.field-meta.xml
<CustomField>
    <fullName>Demand_Partner__c</fullName>
    <label>Demand Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Programmatic_Billing_Landing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Pmp_Type__c.field-meta.xml
<CustomField>
    <fullName>Pmp_Type__c</fullName>
    <label>Pmp Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platform PMP</fullName>
            </value>
            <value>
                <fullName>LG Sales PMP</fullName>
            </value>
            <value>
                <fullName>Programmatic - Others</fullName>
            </value>
            <value>
                <fullName>Partner PMP</fullName>
            </value>
            <value>
                <fullName>LG Sales PMP - Non CTV Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Revenue_Cost__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Cost__c</fullName>
    <label>Revenue/Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
                <isActive>false</isActive>
                <label>Successful</label>
            </value>
            <value>
                <fullName>To Process</fullName>
                <isActive>false</isActive>
                <label>To Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Time_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Time_Bucket__c</fullName>
    <label>Time Bucket</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PGRevenueLandingProcessorBatch.cls
global class PGRevenueLandingProcessorBatch implements Database.Batchable<sObject> {
	
    public static Boolean skipValidations = false;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String strstatus = 'To be processed';
        return Database.getQueryLocator([
            SELECT Id, Status__c, Time_Bucket__c, Opportunity__c, Status_Message__c, 
                   Campaign_Id__c, Campaign_Name__c, Demand_Partner__c, 
                   Pmp_Type__c, Revenue_Cost__c, Deal_Type__c, 
                   Impressions__c, Deal_Type_Formula__c
            FROM Programmatic_Revenue_Landing__c 
            WHERE Status__c = :strstatus
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Programmatic_Revenue_Landing__c> scope) {
        skipValidations = true;
        Map<String, Programmatic_Revenue_Landing__c> hasopp = new Map<String, Programmatic_Revenue_Landing__c>();
        Map<String, Programmatic_Revenue_Landing__c> noopp = new Map<String, Programmatic_Revenue_Landing__c>();
        List<Programmatic_Revenue_Landing__c> lstpgrevfinal = new List<Programmatic_Revenue_Landing__c>();
        Map<String, Deal__c> insdeal = new Map<String, Deal__c>();
        Set<Id> lstopp = new Set<Id>();
        Set<String> pmptype = new Set<String>();
        List<OpportunityLineItem> newOppLineItems = new List<OpportunityLineItem>();
        
        Set<String> productNameSet = new Set<String>();
        
        for (Programmatic_Revenue_Landing__c temp : scope) {
            if (temp.Opportunity__c != null) {
                hasopp.put(temp.Campaign_Id__c, temp);
                lstopp.add(temp.Opportunity__c);
                productNameSet.add(temp.Deal_Type_Formula__c);
            } else {
                noopp.put(temp.Campaign_Id__c, temp);
                pmptype.add(temp.Pmp_Type__c);
            }
        }
        
        // Include both open and closed opportunities
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(
            [SELECT Id, Country__c, Pricebook2Id, recordType.DeveloperName, 
                    Flight_Start_Date__c, Flight_End_Date__c, CurrencyIsoCode 
             FROM Opportunity 
             WHERE Id IN :lstopp]
        );

        List<OpportunityLineItem> oppli = [SELECT Id, Product2.Name, OpportunityId, 
                                             Opportunity.recordType.Name, PricebookEntryId 
                                             FROM OpportunityLineItem 
                                             WHERE OpportunityId IN :lstopp];

        // Create a map to hold PricebookEntries
        Map<String, Id> oppPricebookEntryMap = new Map<String, Id>();

        // Query PricebookEntries
        List<PricebookEntry> pricebookEntries = [SELECT Id, Product2Id, Pricebook2Id, CurrencyIsoCode 
                                                  FROM PricebookEntry 
                                                  WHERE Product2.Name IN :productNameSet 
                                                  AND Pricebook2.IsActive = TRUE];
        
        // Populate map with PricebookEntryId by Product2Id
        for (PricebookEntry pbe : pricebookEntries) {
            oppPricebookEntryMap.put(pbe.Pricebook2Id + '-' + pbe.CurrencyIsoCode, pbe.Id);
        }

        for (Programmatic_Revenue_Landing__c temp : hasopp.values()) {
            Boolean found = false;
            
            for (OpportunityLineItem li : oppli) {
                if (li.OpportunityId == temp.Opportunity__c && li.Product2.Name == temp.Deal_Type_Formula__c && !insdeal.containsKey(temp.Campaign_Id__c)) {
                    found = true;
                    
                    // Create the deal
                    Deal__c d = new Deal__c();
                    d.External_Id__c = temp.Campaign_Id__c + '_' + temp.Time_Bucket__c.formatGMT('yyyy-MM-dd HH:mm:ss');
                    d.Deal_Id__c = temp.Campaign_Id__c;
                    d.Date__c = Date.newInstance(temp.Time_Bucket__c.yearGMT(), temp.Time_Bucket__c.monthGMT(), temp.Time_Bucket__c.dayGMT());
                    d.Deal_Name__c = temp.Campaign_Name__c;
                    d.Deal_Type__c = temp.Deal_Type__c;
                    d.PMP_Type__c = temp.Pmp_Type__c;
                    d.Revenue__c = temp.Revenue_Cost__c;
                    d.Impressions__c = temp.Impressions__c;
                    d.Opportunity_Product__c = li.Id;
                    d.Programmatic_Revenue_Landing__c = temp.Id;
                    insdeal.put(temp.Campaign_Id__c, d);
                    break; // exit the loop when found
                }
            }
            
            // If no matching OpportunityLineItem was found, create a new one
            if (!found) {
                
                System.debug(' ## temp.Deal_Type_Formula__c'+ temp.Deal_Type_Formula__c);
                system.debug('## SELECT Id, Name, Family FROM Product2 '+ [SELECT Id, Name, Family FROM Product2] );
                
                Product2 product = [SELECT Id, Name, Family FROM Product2 WHERE Name = :temp.Deal_Type_Formula__c LIMIT 1];
                if (product != null && oppMap.get(temp.Opportunity__c) != null) {
                    OpportunityLineItem newOppLineItem = new OpportunityLineItem();
                    newOppLineItem.OpportunityId = temp.Opportunity__c;
                    newOppLineItem.Product2Id = product.Id;

                    // Fetch the PricebookEntryId for the product
                    Id pricebookEntryId = oppPricebookEntryMap.get(oppMap.get(temp.Opportunity__c).Pricebook2Id + '-' + oppMap.get(temp.Opportunity__c).CurrencyIsoCode);
                    if (pricebookEntryId != null) {
                        newOppLineItem.PricebookEntryId = pricebookEntryId;
                    } else {
                        // Handle case where no matching PricebookEntry was found
                        System.debug('No PricebookEntry found for product: ' + product.Name);
                        continue;
                    }
                    
                    newOppLineItem.Quantity = 1; // Adjust as per your requirements
                    newOppLineItem.UnitPrice = temp.Revenue_Cost__c;
                    newOppLineItem.Audience_Targeting__c = 'None';
                    newOppLineItem.Product_Full_Name__c = 'System Generated Placeholder Product';
                    
                    newOppLineItem.Flight_Start_Date__c = oppMap.get(temp.Opportunity__c).Flight_Start_Date__c;
                    newOppLineItem.Flight_End_Date__c = oppMap.get(temp.Opportunity__c).Flight_End_Date__c;
                    newOppLineItem.Original_Booking_Amount__c = 0;
                    newOppLineItem.Rate__c = 1;

                    List<String> selectedValues = oppMap.get(temp.Opportunity__c).Country__c.split(';');
                    newOppLineItem.Country__c = selectedValues[0];
                    
                    newOppLineItems.add(newOppLineItem);
                    
                    // Create the deal for the newly created OpportunityLineItem
                    Deal__c d = new Deal__c();
                    d.External_Id__c = temp.Campaign_Id__c + '_' + temp.Time_Bucket__c.formatGMT('yyyy-MM-dd HH:mm:ss');
                    d.Deal_Id__c = temp.Campaign_Id__c;
                    d.Date__c = Date.newInstance(temp.Time_Bucket__c.yearGMT(), temp.Time_Bucket__c.monthGMT(), temp.Time_Bucket__c.dayGMT());
                    d.Deal_Name__c = temp.Campaign_Name__c;
                    d.Deal_Type__c = temp.Deal_Type__c;
                    d.PMP_Type__c = temp.Pmp_Type__c;
                    d.Revenue__c = temp.Revenue_Cost__c;
                    d.Impressions__c = temp.Impressions__c;
                    d.Opportunity_Product__c = null; // Will be updated later after insert
                    d.Programmatic_Revenue_Landing__c = temp.Id;
                    insdeal.put(temp.Campaign_Id__c, d);
                }
            }
        }
        
        // Insert the new OpportunityLineItems and update the deals with the new OpportunityLineItem Ids
        if (!newOppLineItems.isEmpty()) {
            Database.insert(newOppLineItems, false);
            
            for (OpportunityLineItem oli : newOppLineItems) {
                for (Deal__c d : insdeal.values()) {
                    if (d.Opportunity_Product__c == null && d.External_Id__c.startsWith(oli.OpportunityId)) {
                        d.Opportunity_Product__c = oli.Id;
                    }
                }
            }
        }
        
        // Upsert the deals
        List<Deal__c> insd = insdeal.values();
        Database.UpsertResult[] urList = Database.upsert(insd, Deal__c.External_Id__c, false);
        for (Integer i = 0; i < urList.size(); i++) {
            if (urList[i].isSuccess()) {
                Programmatic_Revenue_Landing__c temp = new Programmatic_Revenue_Landing__c();
                temp.Id = insd[i].Programmatic_Revenue_Landing__c;
                temp.Status__c = 'Success';
                temp.Status_Message__c = '';
                lstpgrevfinal.add(temp);
            } else {
                Programmatic_Revenue_Landing__c temp = new Programmatic_Revenue_Landing__c();
                temp.Id = insd[i].Programmatic_Revenue_Landing__c;
                temp.Status__c = 'Error';
                temp.Status_Message__c = String.valueOf(urList[i].getErrors());
                lstpgrevfinal.add(temp);
            }
        }
        
        update lstpgrevfinal;
    }

    global void finish(Database.BatchableContext BC) {}
}