force-app/main/default/objects/Insertion_Order__c/Insertion_Order__c.object-meta.xml
<CustomObject>
    <label>Insertion Order</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insertion Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertion Orders</relationshipLabel>
    <relationshipName>Insertion_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Insertion_Order__c.field-meta.xml
<CustomField>
    <fullName>Insertion_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insertion Order</label>
    <referenceTo>Insertion_Order__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsertionOrderLayoutController.cls
public with sharing class InsertionOrderLayoutController {
  @AuraEnabled(cacheable=true)
  public static Insertion_Order__c getInsertionOrder(string opportunityId) {
    Insertion_Order__c io;
    Insertion_Order__c[] ios = [
      SELECT Id
      FROM Insertion_Order__c
      WHERE Opportunity__c = :opportunityId
      LIMIT 1
    ];

    if (ios.size() > 0) {
      io = ios[0];
    }
    return io;
  }

  @AuraEnabled(cacheable=true)
  public static List<Line_Item__c> getLineItems(string insertionOrderID) {
    return [
      SELECT Id, Name
      FROM Line_Item__c
      WHERE Insertion_Order__c = :insertionOrderID
    ];
  }
}