force-app/main/default/objects/Operational_Placement__c/Operational_Placement__c.object-meta.xml
<CustomObject>
    <label>Operational Placement</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Operational Placement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operational Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operational_Placement__c/fields/Audience_Segment_Details__c.field-meta.xml
<CustomField>
    <fullName>Audience_Segment_Details__c</fullName>
    <label>Audience Segment Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Audience_Targeting__c.field-meta.xml
<CustomField>
    <fullName>Audience_Targeting__c</fullName>
    <label>Audience Targeting</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Daypart__c.field-meta.xml
<CustomField>
    <fullName>Daypart__c</fullName>
    <label>Daypart</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Frequency_Cap__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Cap__c</fullName>
    <label>Frequency Cap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/IO_Impression_Goal__c.field-meta.xml
<CustomField>
    <fullName>IO_Impression_Goal__c</fullName>
    <label>IO Impression Goal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Native_WebOS_Units_App_Based_Exclusions__c.field-meta.xml
<CustomField>
    <fullName>Native_WebOS_Units_App_Based_Exclusions__c</fullName>
    <label>Native WebOS/Units/App Based Exclusions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wedge Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 3.0 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 3.5 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 4.0 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 4.5 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 5.0 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 6.0 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 22 Exclusion</fullName>
            </value>
            <value>
                <fullName>WebOS 23 Exclusion</fullName>
            </value>
            <value>
                <fullName>App Install Base Exclusion</fullName>
            </value>
            <value>
                <fullName>Other.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipName>Operational_Placement_Levels1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Original_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Booking_Amount__c</fullName>
    <label>Original Booking Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Placement_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Placement_Display_Name__c</fullName>
    <label>Placement Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operational_Placement__c/fields/Total_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Booking_Amount__c</fullName>
    <label>Total Booking Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OperationalPlacementHandlerUpsert.cls
public class OperationalPlacementHandlerUpsert {
  @future
  public static void OperationalPlacementUpsert(
    Set<Id> opportunityLineItemsId
  ) {
    list<OpportunityLineItem> opportunityLineItems = [
      SELECT
        id,
        Rate__c,
        Original_Booking_Amount__c,
        IO_Impression_Goal__c,
        Frequency_Cap__c,
        Day_Part__c,
        CurrencyIsoCode,
        TotalPrice,
        Audience_Targeting__c,
        Product_Full_Name__c,
        Total_Booking_Amount__c,
        Start_Date__c,
        UnitPrice,
        End_Date__c
      FROM OpportunityLineItem
      WHERE id IN :opportunityLineItemsId
    ];
    if (opportunityLineItems.size() > 0) {
      system.debug('come in OperationalPlacementUpsert');
      Map<Id, Operational_Placement__c> operationalPlacementsToUpsert = new Map<Id, Operational_Placement__c>();

      Set<Id> oliIds = new Set<Id>();
      for (OpportunityLineItem oli : opportunityLineItems) {
        // This will work for Managed services only : These fields are mandatory for those type of records.
        if(oli.Start_Date__c != null && oli.End_Date__c != null && oli.Total_Booking_Amount__c != null){
          //Date StartDate = oli.Start_Date__c.date();
          //Date EndDate = oli.End_Date__c.date();
          oliIds.add(oli.Id);
          /*try{
          CustomProductSchedulingController.createRevenueSchedules(
            oli.Id,
            StartDate ,
            EndDate,
            oli.Total_Booking_Amount__c,
            'Daily',
            'Divide'
          );
          } catch (DmlException e) {
            System.debug('Error during upsert: ' + e.getMessage());
          }*/
        }
      }
      system.debug('oliIds' + oliIds);
      if (!oliIds.isEmpty()) {
        List<Operational_Placement__c> existingOpsPlacements = [
          SELECT
            Id,
            Opportunity_Product__c,
            Audience_Targeting__c,
            CreatedById,
            CurrencyIsoCode,
            Daypart__c,
            End_Date__c,
            Frequency_Cap__c,
            IO_Impression_Goal__c,
            Native_WebOS_Units_App_Based_Exclusions__c,
            Name,
            Original_Booking_Amount__c,
            OwnerId,
            Placement_Display_Name__c,
            Rate__c,
            Start_Date__c,
            Total_Booking_Amount__c
          FROM Operational_Placement__c
          WHERE Opportunity_Product__c IN :oliIds
        ];
        system.debug('existingOpsPlacements' + existingOpsPlacements);
        for (Operational_Placement__c op : existingOpsPlacements) {
          operationalPlacementsToUpsert.put(op.Opportunity_Product__c, op);
        }
        //DeleteAndCreateSchedules(oliIds, opportunityLineItems);
      }
      List<Operational_Placement__c> opsPlacementsToUpsert = new List<Operational_Placement__c>();

      for (OpportunityLineItem oli : opportunityLineItems) {
        Operational_Placement__c op = operationalPlacementsToUpsert.get(oli.Id);

        if (op == null) {
          system.debug('op' + op);
          op = new Operational_Placement__c();
          op.Opportunity_Product__c = oli.Id;
        }

        op.Placement_Display_Name__c = oli.Product_Full_Name__c;
        // op.Audience_Segment_Details__c = oli.Audience_Segment_Details__c;
        op.Audience_Targeting__c = oli.Audience_Targeting__c;
        op.CurrencyIsoCode = oli.CurrencyIsoCode;
        op.Daypart__c = oli.Day_Part__c;
        op.End_Date__c = Date.valueof(oli.End_Date__c);
        op.Frequency_Cap__c = oli.Frequency_Cap__c;
        op.IO_Impression_Goal__c = String.valueof(oli.IO_Impression_Goal__c);
        op.Original_Booking_Amount__c = oli.Original_Booking_Amount__c;
        op.Rate__c = oli.Rate__c;
        op.Start_Date__c = Date.valueof(oli.Start_Date__c);
        op.Total_Booking_Amount__c = oli.Total_Booking_Amount__c;

        opsPlacementsToUpsert.add(op);
      }
      system.debug('opsPlacementsToUpsert' + opsPlacementsToUpsert);
      if (!opsPlacementsToUpsert.isEmpty()) {
        try {
          upsert opsPlacementsToUpsert;
        } catch (DmlException e) {
          System.debug('Error during upsert: ' + e.getMessage());
        }
      }
    }
  }
}