force-app/main/default/objects/env__c/env__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Environment Variables</label>
</CustomObject>

force-app/main/default/objects/env__c/fields/am_update_api__c.field-meta.xml
<CustomField>
    <fullName>am_update_api__c</fullName>
    <label>am_update_api</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/env__c/fields/pmp_deal_followers__c.field-meta.xml
<CustomField>
    <fullName>pmp_deal_followers__c</fullName>
    <label>pmp_deal_followers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/fields/Account_Trigger_Active__c.field-meta.xml
<CustomField>
    <fullName>Account_Trigger_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Account Trigger Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/fields/Opp_Product_Trigger_Active__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_Trigger_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opp Product Trigger Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/fields/Opp_Seller_Trigger_Active__c.field-meta.xml
<CustomField>
    <fullName>Opp_Seller_Trigger_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opp Seller Trigger Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Settings__c/fields/Opportunity_Triggers_Active__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Triggers_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Opportunity Triggers Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestHelper.cls
public with sharing class TestHelper {
  public static void setupTests() {
    // Insert custom settings
    Trigger_Settings__c ts = new Trigger_Settings__c();
    ts.Account_Trigger_Active__c = true;
    ts.Opp_Seller_Trigger_Active__c = true;
    ts.Opp_Product_Trigger_Active__c = true;
    ts.Opportunity_Triggers_Active__c = true;
    insert ts;
    // Insert env variables
    env__c env = new env__c();
    env.pmp_deal_followers__c = '12345';
    env.am_update_api__c = 'http://dummy.abc.xyz';
    insert env;
  }
}