force-app/main/default/objects/Account/recordTypes/Advertiser.recordType-meta.xml
<RecordType>
    <fullName>Advertiser</fullName>
    <active>true</active>
    <label>Advertiser</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdvertiserController.cls
/**
	* @author Ramesh Kumar Gurusamy
	* @date: 28-Dec-2023
	* @description: Add/update/remove Advertiser.
	* @testClass: Test class for AdvertiserControllerTest.
**/
public class AdvertiserController {
	public Account account;
	public List <Agency__c> agencies {get;set;}
	
	public AdvertiserController(ApexPages.StandardController controller) {
		account = (Account)controller.getRecord();
		agencies = [SELECT Name, Account__c 
					FROM Agency__c 
					WHERE Agency__c=:account.Id];
	}
	
	public PageReference saveRecords() {
		System.debug('***saveRecords***');
		System.debug('agencies***' + agencies);
		try {
			upsert agencies;
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}
	
	public PageReference addRecord() {
		System.debug('***addRecord***');
		try {
			Agency__c agency = new Agency__c();
			agency.Agency__c = account.Id;
			agencies.add(agency);
			System.debug('agency***' + agency);
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}
	
	public PageReference removeRecord() {
		System.debug('***removeRecord***');
		System.debug('***system.currentPageReference()***' + system.currentPageReference());
		System.debug('***system.currentPageReference().getParameters***' + system.currentPageReference().getParameters());
		Integer indexVal = Integer.valueof(System.currentPageReference().getParameters().get('index'));
		try {
			if(agencies[indexVal - 1].Id != null) { delete agencies[indexVal - 1]; }
			agencies.remove(indexVal - 1);
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}}