force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agencies</relationshipLabel>
    <relationshipName>Agencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_region_mapping__mdt/Country_region_mapping__mdt.object-meta.xml
<CustomObject>
    <label>Country region mapping</label>
    <pluralLabel>Country region mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_region_mapping__mdt/fields/All_TimeZone__c.field-meta.xml
<CustomField>
    <fullName>All_TimeZone__c</fullName>
    <label>All TimeZone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_region_mapping__mdt/fields/country_code_2__c.field-meta.xml
<CustomField>
    <fullName>country_code_2__c</fullName>
    <label>country_code_2</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_region_mapping__mdt/fields/country_code_3__c.field-meta.xml
<CustomField>
    <fullName>country_code_3__c</fullName>
    <label>country  code  3</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_region_mapping__mdt/fields/primary_tz__c.field-meta.xml
<CustomField>
    <fullName>primary_tz__c</fullName>
    <label>primary_tz</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <displayFormat>DIS-{0000}</displayFormat>
        <label>Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <label>Discount %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Level__c.field-meta.xml
<CustomField>
    <fullName>Billing_Level__c</fullName>
    <label>Billing Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Impression_Goal__c.field-meta.xml
<CustomField>
    <fullName>IO_Impression_Goal__c</fullName>
    <label>IO Impression Goal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/One_Managed_Service.recordType-meta.xml
<RecordType>
    <fullName>One_Managed_Service</fullName>
    <active>true</active>
    <businessProcess>Managed Service Process</businessProcess>
    <label>1-Managed Service</label>
</RecordType>

force-app/main/default/classes/OpportunityProductHelper.cls
public class OpportunityProductHelper {

    
    
    public static Integer getNumberOfTimezonesByCountry(OpportunityLineItem oppProduct) {
        Integer timezonesCount = 0;
    
        if (oppProduct.Country__c != null) {
            Country_region_mapping__mdt mapping = [
                SELECT All_TimeZone__c
                FROM Country_region_mapping__mdt 
                WHERE MasterLabel = :oppProduct.Country__c
                LIMIT 1
            ];
    
            if (mapping != null && mapping.All_TimeZone__c != null) {
                timezonesCount = mapping.All_TimeZone__c.split('/').size() - 1;
            }
        }
    
        return timezonesCount;
    }

    public static void populateTimeZone(List<OpportunityLineItem> oppProducts) {
        Set<String> countryNames = new Set<String>();
        for (OpportunityLineItem oppProduct : oppProducts) {
            if (oppProduct.Country__c != null) {
                countryNames.add(oppProduct.Country__c);
            }
        }
        
        Map<String, Country_region_mapping__mdt> countryToTimeZoneMap = new Map<String, Country_region_mapping__mdt>();
        if (!countryNames.isEmpty()) {
            for (Country_region_mapping__mdt mapping : [
                SELECT DeveloperName, MasterLabel, All_TimeZone__c, country_code_2__c, country_code_3__c, primary_tz__c
                FROM Country_region_mapping__mdt 
                WHERE MasterLabel IN :countryNames
            ]) {
                countryToTimeZoneMap.put(mapping.MasterLabel, mapping);
            }
        }
        User currentUser = [SELECT TimeZoneSidKey FROM User WHERE Id = :UserInfo.getUserId()];
        for (OpportunityLineItem oppProduct : oppProducts) {
            if (oppProduct.Country__c != null) {
                Country_region_mapping__mdt mapping = countryToTimeZoneMap.get(oppProduct.Country__c);
                if (mapping != null) {
                    oppProduct.Time_Zone__c = mapping.primary_tz__c;
                    
                }
            }
            
            DateTime maxTimeUTC ;
            maxTimeUTC  = oppProduct.Max_Extension_Time__c;
            
            DateTime maxDateTimeUserTimeZone ;
            if(maxTimeUTC != null){
                oppProduct.Max_End_Time_Extension_IO_Timezone__c = timeZoneConvert(oppProduct.Max_Extension_Time__c);
            }
            oppProduct.End_Time_IO_Timezone__c = timeZoneConvert(oppProduct.End_Date__c);
            oppProduct.Start_Time_IO_Timezone__c = timeZoneConvert(oppProduct.Start_Date__c);
        }
    }
    
    public static String timeZoneConvert(DateTime input){
        if(input != null){
            String myDate = input.format('yyyy-MM-dd HH:mm:ss');
            return myDate;
        }else{
            return null;
        }
    }
    
    public static void updateFlightDates(Set<Id> oppIds, Boolean isOppOverride , Map<Id,Opportunity> oppMap) {
        
        // Query opportunities with their line items and record types
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        
        
        List<Opportunity> oppList = [SELECT Id, Flight_Start_Date__c, Flight_End_Date__c, RecordType.DeveloperName,
                                     (SELECT Start_Date__c, End_Date__c, Flight_Start_Date__c, Flight_End_Date__c FROM OpportunityLineItems)
                                     FROM Opportunity 
                                     WHERE Id IN :oppIds];
        
        
        for (Opportunity opp : oppList) {
            Date minStartDate =  null;
            Date maxEndDate = null;
            if(isOppOverride == true){
                minStartDate = oppMap.get(opp.id).Flight_Start_Date__c;
                maxEndDate = oppMap.get(opp.id).Flight_End_Date__c;
            }
            
            
            if (opp.RecordType.DeveloperName == 'One_Managed_Service') {
                
                // Use StartDate and EndDate from OpportunityLineItems
                for (OpportunityLineItem oli : opp.OpportunityLineItems) {
                    
                    if (oli.Start_Date__c != null && (minStartDate == null || convertToUserTimeZone(oli.Start_Date__c) < minStartDate)) {
                        minStartDate = oli.Start_Date__c.date();
                    }
                    if (oli.End_Date__c != null && (maxEndDate == null || convertToUserTimeZone(oli.End_Date__c) > maxEndDate)) {
                        maxEndDate = oli.End_Date__c.date();
                    }
                    
                }
            } else {
                for (OpportunityLineItem oli : opp.OpportunityLineItems) {
                    if (oli.Flight_Start_Date__c != null && (minStartDate == null || convertToUserTimeZone(oli.Flight_Start_Date__c) < minStartDate)) {
                        minStartDate = convertToUserTimeZone(oli.Flight_Start_Date__c);
                    }
                    if (oli.Flight_End_Date__c != null && (maxEndDate == null || convertToUserTimeZone(oli.Flight_End_Date__c) > maxEndDate)) {
                        maxEndDate = convertToUserTimeZone(oli.Flight_End_Date__c);
                    }
                }
            }
            
            if (isOppOverride ||opp.Flight_Start_Date__c != minStartDate || opp.Flight_End_Date__c != maxEndDate) {
                opp.Flight_Start_Date__c = minStartDate;
                opp.Flight_End_Date__c = maxEndDate;
                
                if(isOppOverride && oppMap.get(opp.Id)!= null ){
                    oppMap.get(opp.Id).Flight_Start_Date__c = minStartDate;
                    oppMap.get(opp.Id).Flight_End_Date__c = maxEndDate;
                }else{
                    oppsToUpdate.add(opp);
                }
            }
        }
        
        if (!oppsToUpdate.isEmpty()) {
            update oppsToUpdate;
        }
    }
    
    public static date convertToUserTimeZone(DateTime dt){
        
        Integer timeZoneOffsetMs = UserInfo.getTimeZone().getOffset(dt);
        DateTime userTimeZoneDateTime = dt.addMinutes(timeZoneOffsetMs/60000);
        return  userTimeZoneDateTime.date();
        
    }
    
    /*public static void updateDiscountBasedOnAcc(List<OpportunityLineItem> oli) {
        if (oli.isEmpty()) {
            return; 
        }
        
        Set<Id> oppIds = new Set<Id>();
        for (OpportunityLineItem ol : oli) {
            oppIds.add(ol.OpportunityId);
        }
        
        List<Opportunity> opplist = [SELECT Id, Billing_Level__c, Country__c, Agency__c, AccountId 
                                     FROM Opportunity 
                                     WHERE Id IN :oppIds];
        
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(opplist);
        Set<Id> agencyIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<String> countrySet = new Set<String>();
        
        for (Opportunity opp : opplist) {
            if (opp.Billing_Level__c == 'Account') {
                accountIds.add(opp.AccountId);
            } else if (opp.Billing_Level__c == 'Agency') {
                agencyIds.add(opp.Agency__c);
            }
            if (opp.Country__c != null) {
                countrySet.add(opp.Country__c);
            }
        }
        
        List<Discount__c> discountRecords = [SELECT Id, Account__c, Discount_Percentage__c, Country__c 
                                             FROM Discount__c 
                                             WHERE (Account__c IN :accountIds OR Account__c IN :agencyIds) 
                                             AND Country__c IN :countrySet];
        
        Map<String, Decimal> discountMap = new Map<String, Decimal>();
        for (Discount__c discount : discountRecords) {
            String key = discount.Account__c + ':' + discount.Country__c;
            discountMap.put(key, discount.Discount_Percentage__c);
        }
        
        for (OpportunityLineItem ol : oli) {
            Opportunity opp = oppMap.get(ol.OpportunityId);
            if (opp != null) {
                String key;
                if (opp.Billing_Level__c == 'Account') {
                    key = opp.AccountId + ':' + opp.Country__c;
                } else if (opp.Billing_Level__c == 'Agency') {
                    key = opp.Agency__c + ':' + opp.Country__c;
                }
                
                if (key != null && discountMap.containsKey(key)) {
                    Decimal discountValue = discountMap.get(key);
                    if (discountValue != null ) { 
                        ol.Discount = discountValue; 
                    }
                }
            }
        }
    }*/
    
    
   public static void updateImpressionGoalAmount(List<OpportunityLineItem> lineItemList1) {
       Set<Id> opportunityIds = new Set<Id>();
       for (OpportunityLineItem oli : lineItemList1) {
           opportunityIds.add(oli.OpportunityId);
       }

       List<Opportunity> oppListToUpdate = new List<Opportunity>();
       
       List<Opportunity> oppList = [
           SELECT Id, IO_Impression_Goal__c,(SELECT Id, IO_Impression_Goal__c, OpportunityId FROM OpportunityLineItems)
           FROM Opportunity 
           WHERE Id IN :opportunityIds
       ];
       
       for (Opportunity opp : oppList) {
           Decimal sum = 0; 
           for(OpportunityLineItem oli : opp.OpportunityLineItems){
               if(oli!= null && oli.IO_Impression_Goal__c != null){
               		sum = sum + oli.IO_Impression_Goal__c;
               }
           }
           
           Opportunity oppToUpdate = new Opportunity();	
           oppToUpdate.Id = opp.Id;
           oppToUpdate.IO_Impression_Goal__c = String.valueOf(sum);
           
           oppListToUpdate.add(oppToUpdate);
       }
       
       
       if (!oppListToUpdate.isEmpty()) {
           Database.update(oppListToUpdate, false);
       }
	}
    
    public static void copyProduct(List<OpportunityLineItem> oliNewList) {
        
        // Step 1: Collect Opportunity IDs/ productids where Product2Id is different from Product__c
        Set<Id> productIds = new Set<Id>();
        Set<Id> oppIds = new Set<Id>();
        for (OpportunityLineItem oli : oliNewList) {
            if (oli.Product2Id != oli.Product__c) {
                oppIds.add(oli.OpportunityId);
                productIds.add(oli.Product__c);
            }
        }
        
        // Step 2: Query Opportunities with Pricebook2Id, CurrencyIsoCode
        Map<Id, Opportunity> oppMap = new Map<Id, Opportunity>(
            [SELECT Id, Pricebook2Id, CurrencyIsoCode 
             FROM Opportunity 
             WHERE Id IN :oppIds]
        );
    
        // Step 3: Gather unique Product2 Ids and Pricebook2/Currency combinations
    	Set<Id> pricebookIds = new Set<Id>();
        for (Opportunity opp : oppMap.values()) {
            pricebookIds.add(opp.Pricebook2Id);
        }
    
        // Step 4: Query all relevant PricebookEntry records
        List<PricebookEntry> pricebookEntries = [
            SELECT Id, Product2Id, Pricebook2Id, CurrencyIsoCode 
            FROM PricebookEntry 
            WHERE Product2Id IN :productIds 
              AND Pricebook2Id IN :pricebookIds
              AND IsActive = true
        ];
    
        // Step 5: Create a composite key map (Product2Id + Pricebook2Id + CurrencyIsoCode)
        Map<String, PricebookEntry> pricebookEntryMap = new Map<String, PricebookEntry>();
        for (PricebookEntry pbe : pricebookEntries) {
            String compositeKey = pbe.Product2Id + '_' + pbe.Pricebook2Id + '_' + pbe.CurrencyIsoCode;
            pricebookEntryMap.put(compositeKey, pbe);
        }
    
        // Step 6: Update each OpportunityLineItem with the new Product2Id and PricebookEntryId
        for (OpportunityLineItem oli : oliNewList) {
            Opportunity opp = oppMap.get(oli.OpportunityId);
            if (oli.Product2Id != oli.Product__c && opp != null) {

                // Retrieve the PricebookEntry using the composite key of Product2Id, Pricebook2Id, and CurrencyIsoCode
                String compositeKey = oli.Product__c + '_' + opp.Pricebook2Id + '_' + opp.CurrencyIsoCode;
                PricebookEntry pbe = pricebookEntryMap.get(compositeKey);
    
                if (pbe != null) {
                    oli.PricebookEntryId = pbe.Id;
                    // Set the new Product2Id
                	oli.Product2Id = oli.Product__c;
                } else {
                    System.debug('No active PricebookEntry found for Product2Id: ' + oli.Product__c + 
                                 ', Pricebook2Id: ' + opp.Pricebook2Id + 
                                 ', CurrencyIsoCode: ' + opp.CurrencyIsoCode);
                }
            }
        }
    }


}