force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Direct__c.field-meta.xml
<CustomField>
    <fullName>Client_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewOpportunityTriggerTest.cls
@isTest
public class NewOpportunityTriggerTest {
  // @isTest
  // static void test() {
  //   Test.startTest();

  //   // Constants
  //   String ACCOUNT_NAME = 'Test Account';
  //   String AGENCY_NAME = 'Test Agency';
  //   String OPP_NAME = 'Test Opportunity';

  //   Account acc = new Account(Name = ACCOUNT_NAME);
  //   Account agency = new Account(Name = AGENCY_NAME);
  //   insert acc;
  //   insert agency;

  //   Date flightStartDate = Date.newInstance(2021, 5, 12);
  //   Date flightEndDate = Date.newInstance(2021, 8, 20);

  //   Pricebook2 pb = new Pricebook2(
  //     Name = Constants.PRICEBOOK_MANAGED,
  //     isActive = true
  //   );
  //   insert pb;

  //   // Opportunity without Agency
  //   Opportunity opp1 = new Opportunity(
  //     Name = 'Test Opportunity',
  //     CloseDate = flightEndDate,
  //     StageName = 'RFP received',
  //     Flight_Start_Date__c = flightStartDate,
  //     Flight_End_Date__c = flightEndDate,
  //     AccountId = acc.Id,
  //     Seller_Region__c = 'National Media & Entertainment',
  //     IO_Number_Available__c = 'Not Available',
  //     Market_Type__c = 'M&E',
  // 	Client_Direct__c=TRUE
  //   );
  //   insert opp1;

  //   Opportunity oppRes = [
  //     SELECT Id, Name
  //     FROM Opportunity
  //     WHERE Id = :opp1.Id
  //   ][0];

  //   System.assertEquals(ACCOUNT_NAME + ' - ' + OPP_NAME, oppRes.Name);

  //   // Opportunity with Agency
  //   Opportunity opp2 = new Opportunity(
  //     Name = 'Test Opportunity',
  //     CloseDate = flightEndDate,
  //     StageName = 'RFP received',
  //     Flight_Start_Date__c = flightStartDate,
  //     Flight_End_Date__c = flightEndDate,
  //     AccountId = acc.Id,
  //     Seller_Region__c = 'National Media & Entertainment',
  //     Agency__c = agency.Id,
  //     IO_Number_Available__c = 'Not Available',
  //     Market_Type__c = 'M&E',
  // 	Client_Direct__c=TRUE
  //   );
  //   insert opp2;

  //   oppRes = [SELECT Id, Name FROM Opportunity WHERE Id = :opp2.Id][0];

  //   System.assertEquals(
  //     ACCOUNT_NAME +
  //     ' - ' +
  //     AGENCY_NAME +
  //     ' - ' +
  //     OPP_NAME,
  //     oppRes.Name
  //   );
  // }
}