force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BrandController.cls
/**
	* @author Ramesh Kumar Gurusamy (CFG)
	* @date: 25-Jan-2024
	* @description: Add/update/remove Brand.
	* @testClass: Test class for BrandControllerTest.
**/
public class BrandController {
	public Account account;
	public List <Brand__c> brands {get;set;}
	
	public BrandController(ApexPages.StandardController controller) {
		account = (Account)controller.getRecord();
		brands = [SELECT Name 
                  FROM Brand__c 
                  WHERE Account__c=:account.Id];
	}
	
	public PageReference saveRecords() {
		System.debug('***saveRecords***');
		System.debug('brands***' + brands);
		try {
			upsert brands;
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}
	
	public PageReference addRecord() {
		System.debug('***addRecord***');
		try {
			Brand__c agency = new Brand__c();
			agency.Account__c = account.Id;
			brands.add(agency);
			System.debug('agency***' + agency);
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}
	
	public PageReference removeRecord() {
		System.debug('***removeRecord***');
		System.debug('***system.currentpagereference()***' + system.currentpagereference());
		System.debug('***system.currentpagereference().getparameters***' + system.currentpagereference().getparameters());
		Integer indexVal = Integer.valueof(system.currentpagereference().getparameters().get('index'));
		try {
			if(brands[indexVal - 1].Id != null) { delete brands[indexVal - 1]; }
			brands.remove(indexVal - 1);
			return ApexPages.CurrentPage();
		} catch(Exception e) { System.debug('e***' + e); return null; }
	}
}