force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Net_Term__c.field-meta.xml
<CustomField>
    <fullName>Net_Term__c</fullName>
    <label>Net Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Netsuite_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Account_Name__c</fullName>
    <label>Netsuite Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Demand_Partner.recordType-meta.xml
<RecordType>
    <fullName>Demand_Partner</fullName>
    <active>true</active>
    <label>Demand Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Programmatic_Billing_Landing__c/Programmatic_Billing_Landing__c.object-meta.xml
<CustomObject>
    <label>Programmatic Billing Landing</label>
    <nameField>
        <label>Programmatic Billing Landing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programmatic Billing Landings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programmatic Billing Landings</relationshipLabel>
    <relationshipName>Programmatic_Billing_Landings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Net_term__c.field-meta.xml
<CustomField>
    <fullName>Net_term__c</fullName>
    <label>Net term</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be processed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <label>Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PGBillingLandingProcessorBatch.cls
global class PGBillingLandingProcessorBatch implements Database.Batchable<sObject> {

    private list<Programmatic_Billing_Landing__c> lstpgbillupd = new list<Programmatic_Billing_Landing__c>();
    private list<Programmatic_Billing_Landing__c> lstpgbillfinal = new list<Programmatic_Billing_Landing__c>();
    private map<string,Account> accinsmap = new map<string,Account>();
    private set<Id> success = new set<Id>();
    private set<Id> failed = new set<Id>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String strstatus = 'To be processed';
        return Database.getQueryLocator([
            SELECT Id,Status__c,Demand_Partner__c,Currency_Code__c,Net_term__c,Netsuite_Customer__c,Status_Message__c,Account__c
            FROM Programmatic_Billing_Landing__c 
            WHERE Status__c = :strstatus
            //WHERE Id='a0qVC000002NmncYAC'
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Programmatic_Billing_Landing__c> scope) {
        Set<String> demandpartner = new Set<String>();
       // Id RecordType = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Demand_Partner').getRecordTypeId();
        Id RecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Demand Partner').getRecordTypeId();
        Map<String,Account> accmap = new Map<String,Account>();
        for(Programmatic_Billing_Landing__c sc : scope) {
            if(!demandpartner.contains(sc.Demand_Partner__c))
                demandpartner.add(sc.Demand_Partner__c);
        }
        //Removed record type filter in query.
        List<Account> lstacc = [Select id,Name from Account where Name = :demandpartner];
        if(!lstacc.isEmpty()) {
            for(Account Acc : lstacc) {
                accmap.put(Acc.Name,Acc);
            }
        }
        
        for(Programmatic_Billing_Landing__c sc : scope) {
            if(accmap.containsKey(sc.Demand_Partner__c)){
                sc.Account__c = accmap.get(sc.Demand_Partner__c).Id;
                lstpgbillupd.add(sc);
            } else if (!accinsmap.containsKey(sc.Demand_Partner__c)){
                Account Acctemp = new Account();
                Acctemp.CurrencyIsoCode = sc.Currency_Code__c;
                Acctemp.Name = sc.Demand_Partner__c;
                Acctemp.Netsuite_Account_Name__c = sc.Netsuite_Customer__c;
                Acctemp.Net_Term__c = sc.Net_term__c;
                Acctemp.RecordTypeId = RecordType;
                Acctemp.Type = 'Demand Partner';
                Acctemp.Account_Review_Status__c = 'Approved';
                accinsmap.put(sc.Demand_Partner__c,Acctemp);
            }       
        }
        
        Insert accinsmap.values();       
        for(Programmatic_Billing_Landing__c sc : scope){
            if(accinsmap.containsKey(sc.Demand_Partner__c)){
                sc.Account__c=accinsmap.get(sc.Demand_Partner__c).Id;
                lstpgbillupd.add(sc);
            }
        }
        Database.SaveResult[] srList = Database.update(lstpgbillupd, false);
        for (Database.SaveResult sr : srList){
            if (sr.isSuccess()){
                Programmatic_Billing_Landing__c temp = new Programmatic_Billing_Landing__c();
                temp.Id = sr.getId();
                temp.Status__c = 'Success';
                lstpgbillfinal.add(temp);
            }else{
                Programmatic_Billing_Landing__c temp = new Programmatic_Billing_Landing__c();
                temp.Id = sr.getId();
                temp.Status__c = 'Failed';
                String error;
                for (Database.Error err : sr.getErrors()){
                    error = String.valueOf(err.getMessage());
                }
                temp.Status_Message__c = error;
                lstpgbillfinal.add(temp);
            }
        }
        Update lstpgbillfinal;
    }

    global void finish(Database.BatchableContext BC) {
        // Optional: Add any post-processing logic here
    }

}