force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Contact?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Programmatic_Revenue_Landing__c.field-meta.xml
<CustomField>
    <fullName>Programmatic_Revenue_Landing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programmatic Revenue Landing</label>
    <referenceTo>Programmatic_Revenue_Landing__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dropbox_URL__c.field-meta.xml
<CustomField>
    <fullName>Dropbox_URL__c</fullName>
    <label>Dropbox URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Impression_Goal__c.field-meta.xml
<CustomField>
    <fullName>IO_Impression_Goal__c</fullName>
    <label>IO Impression Goal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Point_Of_Contact_Primary__c.field-meta.xml
<CustomField>
    <fullName>Main_Point_Of_Contact_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Point Of Contact (Primary)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Main Point Of Contact (Primary))</relationshipLabel>
    <relationshipName>Opportunities_MainPOC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Booking_Amount__c</fullName>
    <label>Original Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Secondary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Secondary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/Programmatic_Revenue_Landing__c.object-meta.xml
<CustomObject>
    <label>Programmatic Revenue Landing</label>
    <nameField>
        <label>Programmatic Revenue Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programmatic Revenue Landing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <externalId>true</externalId>
    <label>Campaign Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Demand_Partner__c.field-meta.xml
<CustomField>
    <fullName>Demand_Partner__c</fullName>
    <label>Demand Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Programmatic_Billing_Landing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
                <isActive>false</isActive>
                <label>Successful</label>
            </value>
            <value>
                <fullName>To Process</fullName>
                <isActive>false</isActive>
                <label>To Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Programmatic_Revenue_Landing__c/fields/Time_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Time_Bucket__c</fullName>
    <label>Time Bucket</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PGRevenueLandingProcessorBatchTest.cls
@isTest
public class PGRevenueLandingProcessorBatchTest {
    
    @isTest
    static void testBatch() {
        
        // Set up test data
        Date flightStartDate = Date.newInstance(2021, 5, 12);
        Date flightEndDate = Date.newInstance(2021, 8, 20);
        Date bookingDate = Date.newInstance(2021, 3, 12);
    
        Double CPM = 15.0;
        Integer MinImpressions = 10000;
        List<Opportunity> opps = new List<Opportunity>();
        List<OpportunityLineItem> oppLineItems = new List<OpportunityLineItem>();
        List<Programmatic_Revenue_Landing__c> programmaticRevenueLandings = new List<Programmatic_Revenue_Landing__c>();
        List<Deal__c> deals = new List<Deal__c>();
        
       Account acc = new Account(name='test acc123@qwe');
        insert acc;
        acc.Account_Review_Status__c='Approved';
        update acc;
        Account acc2 = new Account(name='agency acc12322');
        acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        insert acc2;
        acc2.Account_Review_Status__c='Approved';
        update acc2;
        Contact contact1 = new Contact(FirstName='Ricky111', LastName='Pointing');
        contact1.AccountId = acc.Id;
        contact1.Is_Billing_Contact__c = TRUE;
        contact1.Email = '12test.user1@example.com';
        insert contact1;
        Contact contact2 = new Contact(FirstName='12Bark', LastName='Putin');
        contact2.Email = '12test.user2@example.com';
        contact2.AccountId = acc.Id;
        insert contact2;
        Contact contact3 = new Contact(FirstName='22Test', LastName='Data');
        contact3.Email = '221test.user3@example.com';
        contact3.AccountId = acc.Id;
        insert contact3;
        Opportunity opp = new Opportunity(Name='test opp',Primary_Billing_Contact__c=contact1.Id,Secondary_Billing_Contact__c=contact2.Id, Amount=100, TotalOpportunityQuantity=10, CloseDate=System.today(), AccountId=acc.Id);
        opp.Seller_Region__c = 'National Media & Entertainment';
        opp.Brand_Name__c = 'Test';
        opp.StageName = 'RFP received';
        opp.Dropbox_URL__c = 'http://nnnn';
        opp.Flight_End_Date__c = Date.newInstance(2021, 5, 30);
        opp.Flight_Start_Date__c = Date.newInstance(2021, 5, 1);
        opp.Seller_Region__c = 'National Media & Entertainment';
        opp.Brand_Id__c = '1111';
        opp.IO_Number_Available__c = 'Not Available';
        opp.CSM__c = UserInfo.getUserId();
        opp.Market_Type__c = 'M&E';
        opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
        opp.Agency__c = acc2.Id;
        opp.Campaign_Name__c = 'test camp';
        insert opp;
        
        Product2 productNative = new Product2(
      Name = 'Programmatic PMP',
      ProductCode = 'Code',
      isActive = true,
      Family = 'Managed Service Impressions',
      CanUseRevenueSchedule = true
    );

    insert productNative;
        
    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;
    Id pricebookId = Test.getStandardPricebookId();

    PricebookEntry pbEntryNativeStandard = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    PricebookEntry pbEntryNative = new PricebookEntry(
      Pricebook2Id = pb.id,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    insert new List<PricebookEntry>{ pbEntryNativeStandard, pbEntryNative };

    OpportunityLineItem oliCTVNative = new OpportunityLineItem(
            PricebookEntryId = pbEntryNative.id,
            UnitPrice = 1000,
        	Rate__c = 0,
			Original_Booking_Amount__c = 1000,
		    Total_Booking_Amount__c = 1000,
            IO_Impression_Goal__c = 2,
            Audience_Targeting__c = '1P ACR',
            Device_Type__c = 'CTV',
            Placement_Billing_Name__c = 'test Placement',
            Placement_Category__c = 'Added Value',
            Placement_Type__c = 'ROS',
        	Audience_Segment_Details__c = 'Test segment',
      		Product_Full_Name__c = 'test Placement',
            End_Date__c = system.now(),
            Product_Family__c = 'Managed Service Impressions',
            OpportunityId = opp.Id,
            Flight_Start_Date__c = flightStartDate,
            Flight_End_Date__c = flightEndDate,
            MinImpressions__c = MinImpressions,
            CPM__c = CPM,
            Country__c = 'India',
        	BETA_Program__c = 'Content Store RB Beta Program',
        	IO_Product_Display_Name__c = 'Programmatic Guaranteed'
        );
        insert oliCTVNative;
        
        // Create Programmatic_Revenue_Landing__c records
        Programmatic_Revenue_Landing__c prlWithOpp = new Programmatic_Revenue_Landing__c(
            Status__c = 'To be processed',
            Time_Bucket__c = Date.today(),
            Opportunity__c = opp.Id,
            Campaign_Id__c = 'Campaign_1',
            Campaign_Name__c = 'Campaign Name 1',
            Demand_Partner__c = 'Partner 1',
            Pmp_Type__c = 'test acc123@qwe_agency acc12322_ _test camp_5/1/21 - 8/20/21 CTV Native',
            Revenue_Cost__c = 1000,
            Deal_Type__c = 'Deal Type 1',
            Impressions__c = 1000
        );
        programmaticRevenueLandings.add(prlWithOpp);
        
        Programmatic_Revenue_Landing__c prlWithoutOpp = new Programmatic_Revenue_Landing__c(
            Status__c = 'To be processed',
            //Time_Bucket__c = Date.today(),
            Opportunity__c = null,
            Campaign_Id__c = 'Campaign_2',
            Campaign_Name__c = 'Campaign Name 2',
            Demand_Partner__c = 'Partner 2',
            Pmp_Type__c = 'Type 2',
            Revenue_Cost__c = 2000,
            Deal_Type__c = 'Deal Type 2',
            Impressions__c = 2000
        );
        programmaticRevenueLandings.add(prlWithoutOpp);
        
        insert programmaticRevenueLandings;
        
        // Run the batch class
        Test.startTest();
        Database.executeBatch(new PGRevenueLandingProcessorBatch(), 200);
        Test.stopTest();
        
       }
    
    @isTest
    static void testBatchWithNoOpportunityLineItems() {
        Account acc = new Account(name='test acc');
        insert acc;
        acc.Account_Review_Status__c='Approved';
        update acc;
        Account acc2 = new Account(name='agency acc');
        acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
        insert acc2;
        acc2.Account_Review_Status__c='Approved';
        update acc2;
        Contact contact1 = new Contact(FirstName='Ricky', LastName='Pointing');
        contact1.AccountId = acc.Id;
        contact1.Is_Billing_Contact__c = TRUE;
        contact1.Email = 'test.user1@example.com';
        insert contact1;
        Contact contact2 = new Contact(FirstName='Bark', LastName='Putin');
        contact2.Email = 'test.user2@example.com';
        contact2.AccountId = acc.Id;
        insert contact2;
        Contact contact3 = new Contact(FirstName='Test', LastName='Data');
        contact3.Email = 'test.user3@example.com';
        contact3.AccountId = acc.Id;
        insert contact3;
        Opportunity opp = new Opportunity(Name='test opp',Primary_Billing_Contact__c=contact1.Id,Secondary_Billing_Contact__c=contact2.Id, Amount=100, TotalOpportunityQuantity=10, CloseDate=System.today(), AccountId=acc.Id);
        opp.Seller_Region__c = 'National Media & Entertainment';
        opp.Brand_Name__c = 'Test';
        opp.Dropbox_URL__c = 'http://nnnn';
        opp.StageName = 'RFP received';
        opp.Flight_End_Date__c = Date.newInstance(2021, 5, 30);
        opp.Flight_Start_Date__c = Date.newInstance(2021, 5, 1);
        opp.Seller_Region__c = 'National Media & Entertainment';
        opp.Brand_Id__c = '1111';
        opp.IO_Number_Available__c = 'Not Available';
        opp.CSM__c = UserInfo.getUserId();
        opp.Market_Type__c = 'M&E';
        opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
        opp.Agency__c = acc2.Id;
        opp.Campaign_Name__c = 'test camp';
        insert opp;
        
        
         Product2 productNative = new Product2(
      Name = 'Programmatic Guaranteed',
      ProductCode = 'Code',
      isActive = true,
      Family = 'Managed Service Impressions',
      CanUseRevenueSchedule = true
    );

    insert productNative;
        
    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;
    Id pricebookId = Test.getStandardPricebookId();

    PricebookEntry pbEntryNativeStandard = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    PricebookEntry pbEntryNative = new PricebookEntry(
      Pricebook2Id = pb.id,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    insert new List<PricebookEntry>{ pbEntryNativeStandard, pbEntryNative };
        
        Programmatic_Revenue_Landing__c prlWithNoLineItems = new Programmatic_Revenue_Landing__c(
            Status__c = 'To be processed',
            //Time_Bucket__c = Date.today(),
            Opportunity__c = opp.Id,
            Campaign_Id__c = 'Campaign_No_Line_Items',
            Campaign_Name__c = 'Campaign No Line Items',
            Demand_Partner__c = 'Partner No Line Items',
            Pmp_Type__c = 'Type No Line Items',
            Deal_Type__c = 'programmatic_guarantee',
            Revenue_Cost__c = 3000,
            Impressions__c = 3000
        );
        insert prlWithNoLineItems;
        
        Test.startTest();
        //Database.executeBatch(new PGRevenueLandingProcessorBatch(), 200);
        String cronExp = '0 0 0 ? * MON-FRI'; // Every weekday at midnight
        System.schedule('Test PGRevenueLandingProcessorBatchScheduler', cronExp, new PGRevenueLandingProcessorBatchScheduler());
        Test.stopTest();
        
        /*Programmatic_Revenue_Landing__c prlResult = [SELECT Id, Status__c, Status_Message__c FROM Programmatic_Revenue_Landing__c WHERE Id = :prlWithNoLineItems.Id];
        System.assertEquals('Error', prlResult.Status__c, 'Expected the record without matching OpportunityLineItems to have an error status.');
        System.assertEquals('Products not present on the opportunity.', prlResult.Status_Message__c, 'Expected error message for missing OpportunityLineItems.');*/
    }
}