force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Contact?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Direct__c.field-meta.xml
<CustomField>
    <fullName>Client_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dropbox_URL__c.field-meta.xml
<CustomField>
    <fullName>Dropbox_URL__c</fullName>
    <label>Dropbox URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Name_Manual_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_Name_Manual_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Name Manual Update?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Point_Of_Contact_Primary__c.field-meta.xml
<CustomField>
    <fullName>Main_Point_Of_Contact_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Point Of Contact (Primary)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Main Point Of Contact (Primary))</relationshipLabel>
    <relationshipName>Opportunities_MainPOC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_KPI__c.field-meta.xml
<CustomField>
    <fullName>Primary_KPI__c</fullName>
    <label>Primary KPI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App Engagement</fullName>
            </value>
            <value>
                <fullName>App Engagement - App Launches</fullName>
            </value>
            <value>
                <fullName>Awareness/Unique Reach</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>Delivery In Full</fullName>
            </value>
            <value>
                <fullName>Delivery in Full - Evenly Pacing</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Frequency</fullName>
            </value>
            <value>
                <fullName>In Geo</fullName>
            </value>
            <value>
                <fullName>Tune in (show/movie)</fullName>
            </value>
            <value>
                <fullName>VCR</fullName>
            </value>
            <value>
                <fullName>Viewability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Secondary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Secondary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_KPI__c.field-meta.xml
<CustomField>
    <fullName>Secondary_KPI__c</fullName>
    <label>Secondary KPI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App Engagement</fullName>
            </value>
            <value>
                <fullName>App Engagement - App Launches</fullName>
            </value>
            <value>
                <fullName>App install</fullName>
            </value>
            <value>
                <fullName>Awareness/Unique Reach</fullName>
            </value>
            <value>
                <fullName>Brand Safety</fullName>
            </value>
            <value>
                <fullName>Conversion (location attribution)</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>Delivery In Full</fullName>
            </value>
            <value>
                <fullName>Delivery in Full - Evenly Pacing</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Frequency</fullName>
            </value>
            <value>
                <fullName>In Geo</fullName>
            </value>
            <value>
                <fullName>Tune in (show/movie)</fullName>
            </value>
            <value>
                <fullName>VCR</fullName>
            </value>
            <value>
                <fullName>Viewability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerTest.cls
/* 
	@author		 : Ramesh Kumar Gurusamy
	@team		   : CFG
	@createdDate	: 23-Dec-2023
	@description	: Test class for OpportunityTrigger.
*/
@isTest
public class OpportunityTriggerTest {
	static testMethod void testCreateOpp() {
        Date flightStartDate = Date.newInstance(2021, 5, 12);
        Date flightEndDate = Date.newInstance(2021, 8, 20);
        Date bookingDate = Date.newInstance(2021, 3, 12);
		Account acc = new Account(name='test acc');
		insert acc;
        acc.Account_Review_Status__c='Approved';
        update acc;
		Account acc2 = new Account(name='agency acc');
		acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
		insert acc2;
        acc2.Account_Review_Status__c='Approved';
        update acc2;
		Contact contact1 = new Contact(FirstName='Ricky', LastName='Pointing');
		contact1.AccountId = acc.Id;
		contact1.Is_Billing_Contact__c = TRUE;
		contact1.Email = 'test.user1@example.com';
		insert contact1;
		Contact contact2 = new Contact(FirstName='Bark', LastName='Putin');
		contact2.Email = 'test.user2@example.com';
		contact2.AccountId = acc.Id;
		insert contact2;
		Contact contact3 = new Contact(FirstName='Test', LastName='Data');
		contact3.Email = 'test.user3@example.com';
		contact3.AccountId = acc.Id;
		insert contact3;
		Opportunity opp = new Opportunity(Name='test opp',Primary_Billing_Contact__c=contact1.Id,Secondary_Billing_Contact__c=contact2.Id, Amount=100, TotalOpportunityQuantity=10, StageName='Prospecting', CloseDate=System.today(), AccountId=acc.Id);
		opp.Seller_Region__c = 'National Media & Entertainment';
		opp.Brand_Name__c = 'Test';
		opp.Brand_Id__c = '1111';
        opp.Dropbox_URL__c = 'http://nnnn';
		opp.IO_Number_Available__c = 'Not Available';
		opp.CSM__c = UserInfo.getUserId();
		opp.Market_Type__c = 'M&E';
		opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
		opp.Agency__c = acc2.Id;
		opp.Campaign_Name__c = 'test camp';
        opp.Flight_Start_Date__c = flightStartDate;
      	opp.Flight_End_Date__c = flightEndDate;
		insert opp;
		opp.Secondary_Billing_Contact__c = contact3.Id;
		opp.Campaign_Name__c = 'test camp2';
		update opp;
		opp.Primary_Billing_Contact__c = contact2.Id;
		opp.Campaign_Name__c = '';
		update opp;
		opp.Secondary_Billing_Contact__c = contact1.Id;
		update opp;
		opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
		update opp;
		//opp.Main_Point_Of_Contact_Primary__c = contact2.Id;
		//update opp;
		Test.startTest();
		opp.Primary_Billing_Contact__c = null;
		opp.Secondary_Billing_Contact__c = null;
		opp.Main_Point_Of_Contact_Primary__c = null;
		opp.Agency__c = acc2.Id;
		update opp;
		opp.Primary_Billing_Contact__c = contact1.Id;
		opp.Secondary_Billing_Contact__c = contact2.Id;
		//opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
		//opp.Agency__c = null;
		//opp.Client_Direct__c = TRUE;
		update opp;
        List<Opportunity> lstopp = new List<Opportunity>();
		Opportunity opp2 = new Opportunity(Name='test opp2', Amount=100, TotalOpportunityQuantity=10, StageName='Prospecting', CloseDate=System.today(), AccountId=acc.Id);
		opp2.Seller_Region__c = 'National Media & Entertainment';
		opp2.Brand_Name__c = 'Test';
		opp2.Brand_Id__c = '1111';
        opp2.Dropbox_URL__c = 'http://nnnn';
		opp2.IO_Number_Available__c = 'Not Available';
		opp2.CSM__c = UserInfo.getUserId();
		opp2.Market_Type__c = 'M&E';
		opp2.Agency__c = acc2.Id;
        opp2.Flight_Start_Date__c = flightStartDate;
      	opp2.Flight_End_Date__c = flightEndDate;
		insert opp2;
		opp2.Is_Name_Manual_Update__c = FALSE;
        opp2.StageName='Proposal submitted';
        opp2.Campaign_Name__c = 'test';
        opp2.Primary_KPI__c = 'In Geo';
        opp2.Secondary_KPI__c = 'Fraud';
        opp2.X3P_Verification_Partner__c = 'IAS : Brand Safety';
		//opp2.Agency__c = null;
		//opp2.Client_Direct__c = TRUE;
		update opp2;
        lstopp.add(opp2);
        OpportunityTriggerHandler.deleteAgency(lstopp);
        list<Opportunity_Billing_Ad_Server__c> oldRecords = new list<Opportunity_Billing_Ad_Server__c>();
          Opportunity_Billing_Ad_Server__c  objBAdserver = new Opportunity_Billing_Ad_Server__c();
          objBAdserver.Billing_Ad_Server__c = 'Innovid';
          objBAdserver.Product__c = 'Cross Device Display' ; 
          objBAdserver.Opportunity__c = opp.Id;
          insert objBAdserver;
      	oldRecords.add(objBAdserver);
     // BillingAdserverHandler.beforeDelete(oldRecords);
        try{
            delete objBAdserver;
        	delete opp2;
        }catch(Exception e ){
           system.debug('Getting Error: '+e );
        }
        
		Test.stopTest();
	}
    
    static testMethod void testCreateParentOpp() {
    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);
    Date bookingDate = Date.newInstance(2021, 3, 12);
    Account acc = new Account(name = 'test acc');
    insert acc;
    acc.Account_Review_Status__c = 'Approved';
    update acc;
    Account acc2 = new Account(name = 'agency acc');
    acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Agency')
      .getRecordTypeId();
    insert acc2;
    acc2.Account_Review_Status__c = 'Approved';
    update acc2;
    Contact contact1 = new Contact(FirstName = 'Ricky', LastName = 'Pointing');
    contact1.AccountId = acc.Id;
    contact1.Is_Billing_Contact__c = true;
    contact1.Email = 'test.user1@example.com';
    insert contact1;
    Contact contact2 = new Contact(FirstName = 'Bark', LastName = 'Putin');
    contact2.Email = 'test.user2@example.com';
    contact2.AccountId = acc.Id;
    insert contact2;
    Contact contact3 = new Contact(FirstName = 'Test', LastName = 'Data');
    contact3.Email = 'test.user3@example.com';
    contact3.AccountId = acc.Id;
    insert contact3;
    String parentOppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Parent Opportunity').getRecordTypeId();
    Opportunity opp = new Opportunity(
      RecordTypeId=parentOppRecordTypeId,
      Name = 'test opp',
      Dropbox_URL__c = 'http://nnnn',
      Primary_Billing_Contact__c = contact1.Id,
      Secondary_Billing_Contact__c = contact2.Id,
      Amount = 100,
      TotalOpportunityQuantity = 10,
      StageName = 'Prospecting',
      CloseDate = System.today(),
      AccountId = acc.Id
    );
    opp.Seller_Region__c = 'National Media & Entertainment';
    opp.Brand_Name__c = 'Test';
    opp.Brand_Id__c = '1111';
    opp.IO_Number_Available__c = 'Not Available';
    opp.CSM__c = UserInfo.getUserId();
    opp.Market_Type__c = 'M&E';
    opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
    opp.Agency__c = acc2.Id;
    opp.Campaign_Name__c = 'test camp';
    opp.Flight_Start_Date__c = flightStartDate;
    opp.Flight_End_Date__c = flightEndDate;
    insert opp;
    opp.Secondary_Billing_Contact__c = contact3.Id;
    opp.Campaign_Name__c = 'test camp2';
    update opp;
    opp.Primary_Billing_Contact__c = contact2.Id;
    opp.Campaign_Name__c = '';
    update opp;
    opp.Secondary_Billing_Contact__c = contact1.Id;
    update opp;
    opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
    update opp;
    //opp.Main_Point_Of_Contact_Primary__c = contact2.Id;
    //update opp;
    Test.startTest();
    opp.Primary_Billing_Contact__c = null;
    opp.Secondary_Billing_Contact__c = null;
    opp.Main_Point_Of_Contact_Primary__c = null;
    opp.Agency__c = acc2.Id;
    update opp;
    opp.Primary_Billing_Contact__c = contact1.Id;
    opp.Secondary_Billing_Contact__c = contact2.Id;
    //opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
    //opp.Agency__c = null;
    //opp.Client_Direct__c = TRUE;
    update opp;
    List<Opportunity> lstopp = new List<Opportunity>();
    Opportunity opp2 = new Opportunity(
      Name = 'test opp2',
      Amount = 100,
      Dropbox_URL__c = 'http://nnnn',
      TotalOpportunityQuantity = 10,
      StageName = 'Prospecting',
      CloseDate = System.today(),
      AccountId = acc.Id
    );
    opp2.Seller_Region__c = 'National Media & Entertainment';
    opp2.Brand_Name__c = 'Test';
    opp2.Brand_Id__c = '1111';
    opp2.IO_Number_Available__c = 'Not Available';
    opp2.CSM__c = UserInfo.getUserId();
    opp2.Market_Type__c = 'M&E';
    opp2.Agency__c = acc2.Id;
    opp2.Flight_Start_Date__c = flightStartDate;
    opp2.Flight_End_Date__c = flightEndDate;
    insert opp2;
    opp2.Is_Name_Manual_Update__c = false;
    opp2.StageName = 'Proposal submitted';
    opp2.Campaign_Name__c = 'test';
    opp2.Primary_KPI__c = 'In Geo';
    opp2.Secondary_KPI__c = 'Fraud';
    opp2.X3P_Verification_Partner__c = 'IAS : Brand Safety';
    //opp2.Agency__c = null;
    //opp2.Client_Direct__c = TRUE;
    update opp2;
    lstopp.add(opp2);
    OpportunityTriggerHandler.deleteAgency(lstopp);
    list<Opportunity_Billing_Ad_Server__c> oldRecords = new List<Opportunity_Billing_Ad_Server__c>();
    Opportunity_Billing_Ad_Server__c objBAdserver = new Opportunity_Billing_Ad_Server__c();
    objBAdserver.Billing_Ad_Server__c = 'Brightroll';
    objBAdserver.Product__c = 'Cross Device Video';
    objBAdserver.Opportunity__c = opp.Id;
    insert objBAdserver;
    oldRecords.add(objBAdserver);
    // BillingAdserverHandler.beforeDelete(oldRecords);
    try{
            delete objBAdserver;
    		delete opp2;
        }catch(Exception e ){
           system.debug('Getting Error: '+e );
        }
    
    Test.stopTest();
  }
}