force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Net_Term__c.field-meta.xml
<CustomField>
    <fullName>Net_Term__c</fullName>
    <label>Net Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NetSuite_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Internal_ID__c</fullName>
    <label>NetSuite Internal ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Programmatic_Billing_Landing__c/Programmatic_Billing_Landing__c.object-meta.xml
<CustomObject>
    <label>Programmatic Billing Landing</label>
    <nameField>
        <label>Programmatic Billing Landing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programmatic Billing Landings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Net_term__c.field-meta.xml
<CustomField>
    <fullName>Net_term__c</fullName>
    <label>Net term</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programmatic_Billing_Landing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be processed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PGBillingLandingProcessorBatchTest.cls
@isTest
private class PGBillingLandingProcessorBatchTest {
    
    @isTest
    static void setupTestData() {
        Account demandPartner = new Account(
            Name = 'Test Demand Partner',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Demand Partner').getRecordTypeId(),
            CurrencyIsoCode = 'USD',
            NetSuite_Internal_ID__c = 'NS123',
            Net_Term__c = '30',
            Type = 'Demand Partner',
            Account_Review_Status__c = 'Approved'
        );
        insert demandPartner;
        list<Programmatic_Billing_Landing__c> lstpbl = new list<Programmatic_Billing_Landing__c>();
        Programmatic_Billing_Landing__c billingRecord1 = new Programmatic_Billing_Landing__c(
            Status__c = 'To be processed',
            Demand_Partner__c = 'Test Demand Partner',
            Currency_Code__c = 'USD',
            Net_term__c = '30',
            Netsuite_Customer__c = 'NS123'
        );
        lstpbl.add(billingRecord1);
        Programmatic_Billing_Landing__c billingRecord2 = new Programmatic_Billing_Landing__c(
            Status__c = 'To be processed',
            Demand_Partner__c = 'New Demand Partner',
            Currency_Code__c = 'EUR',
            Net_term__c = '15',
            Netsuite_Customer__c = 'NS456'
        );
        lstpbl.add(billingRecord2);
        
        insert lstpbl;
        
        Test.startTest();
        
        PGBillingLandingProcessorBatchScheduler abs= new PGBillingLandingProcessorBatchScheduler();
        String cronExpr = '0 0 0 15 3 ? 2025';
        String jobId = System.schedule('myJobTestJobName', cronExpr, abs);
        abs.execute(null);
        
        Test.stopTest();
    }
}