force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Direct__c.field-meta.xml
<CustomField>
    <fullName>Client_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dropbox_URL__c.field-meta.xml
<CustomField>
    <fullName>Dropbox_URL__c</fullName>
    <label>Dropbox URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Impression_Goal__c.field-meta.xml
<CustomField>
    <fullName>IO_Impression_Goal__c</fullName>
    <label>IO Impression Goal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Booking_Amount__c</fullName>
    <label>Original Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Seller__c/Opportunity_Product_Seller__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Seller</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Opportunity Product Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Seller__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product Sellers</relationshipLabel>
    <relationshipName>Opportunity_Product_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Product_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Seller__c/fields/Seller_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Seller_Percentage__c</fullName>
    <label>Seller Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity_Seller__c/Opportunity_Seller__c.object-meta.xml
<CustomObject>
    <label>Opportunity Seller</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Opportunity Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Sellers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Seller__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Sellers</relationshipLabel>
    <relationshipName>Opportunity_Sellers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunitySellerUpdateTriggerTest.cls
@isTest(isParallel=false)
public class OpportunitySellerUpdateTriggerTest {
  @isTest
  static void opportnitySellerUpdateTest() {
    TestHelper.setupTests();
    Test.startTest();
    Boolean exceptionThrown = false;
    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);

    User u = new user();
    u.LastName = 'Test Code';
    u.Email = 'test@test.com';
    u.Alias = 'Tcode';
    u.Username = 'test-lgads@test.com';
    u.CommunityNickname = 'test12';
    u.LocaleSidKey = 'en_US';
    u.TimeZoneSidKey = 'GMT';
    u.ProfileID = '00e5Y000001yOPUQA2';
    u.LanguageLocaleKey = 'en_US';
    u.EmailEncodingKey = 'UTF-8';
    insert u;

     Account acc1 = new Account(
      Name = 'Test Account',
      Type = Constants.ACCOUNT_TYPE_BRAND
    );

    insert acc1;
	account acc = new account(id = acc1.Id,
      Account_Review_Status__c = 'Approved');
    update acc;

    Contact contact1 = new Contact(
      LastName = 'Account Contact',
      AccountId = acc.Id,
      Email = 'test@gmail.com'
    );
    insert contact1;

    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = system.today(),
      StageName = 'RFP received',
      Flight_Start_Date__c = system.today(),
      Flight_End_Date__c = system.today(),
      AccountId = acc.Id,
      Dropbox_URL__c = 'http://nnnn',
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E',
	  Client_Direct__c=TRUE,
      Campaign_Name__c = 'test'
    );
    insert opp;

    List<Opportunity_Seller__c> osList = [
      SELECT id, Opportunity__c, Seller__c, Percentage__c
      FROM Opportunity_Seller__c
      WHERE Opportunity__c = :opp.Id AND Seller__c = :UserInfo.getUserId()
    ];

    Opportunity_Seller__c os1 = osList[0];
    os1.Percentage__c = 50;
    update os1;

    Opportunity_Seller__c os2 = new Opportunity_Seller__c(
      Opportunity__c = opp.Id,
      Seller__c = u.Id,
      Percentage__c = 50
    );
    insert os2;

    try {
      exceptionThrown = false;
      os2.Percentage__c = 60;
      update os2;
    } catch (Exception e) {
      exceptionThrown = true;
      System.assert(
        e.getMessage()
          .contains('Total Percentage from all sellers cannot be more than 100')
      );
    } finally {
      os2.Percentage__c = 50;
      System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      os2.Seller__c = UserInfo.getUserId();
      System.debug(UserInfo.getUserId() + ' -> ' + u.Id);
      update os2;
    } catch (Exception e) {
      exceptionThrown = true;
      System.assert(
        e.getMessage().contains('Cannot add the same seller twice')
      );
    } finally {
      os2.Percentage__c = 50;
      System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }
    Test.StopTest();
  }

  @isTest
  static void opportnityProductSellerSyncTest() {
    Test.startTest();
    Boolean exceptionThrown = false;
    Id pricebookId = Test.getStandardPricebookId();

    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);

    Double CPM = 15.0;
    Integer MinImpressions = 10000;

     Account acc1 = new Account(
      Name = 'Test Account',
      Type = Constants.ACCOUNT_TYPE_BRAND
    );

    insert acc1;
	account acc = new account(id = acc1.Id,
      Account_Review_Status__c = 'Approved');
    update acc;

    Contact contact1 = new Contact(
      LastName = 'Account Contact',
      AccountId = acc.Id,
       Email = 'test@gmail.com'
    );
    insert contact1;

    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;

    Product2 productNative = new Product2(
      Name = 'CTV native',
      ProductCode = 'Code',
      isActive = true,
      Family = 'Managed Service Impressions',
      CanUseRevenueSchedule = true
    );
    insert productNative;

    PricebookEntry pbEntryNative = new PricebookEntry(
      Pricebook2Id = pb.Id,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    PricebookEntry pbEntryNativeStandard = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    insert new List<PricebookEntry>{ pbEntryNativeStandard, pbEntryNative };

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = system.today(),
      StageName = 'RFP received',
      Dropbox_URL__c = 'http://nnnn',
      Flight_Start_Date__c = system.today(),
      Flight_End_Date__c = system.today(),
      AccountId = acc.Id,
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E',
	  Client_Direct__c=TRUE,
      Campaign_Name__c = 'test'
    );
    insert opp;

    OpportunityLineItem oliCTVNative1 = new OpportunityLineItem(
            PricebookEntryId = pbEntryNative.id,
            UnitPrice = 1000,
        	Rate__c = 0,
			Original_Booking_Amount__c = 1000,
		    Total_Booking_Amount__c = 1000,
            IO_Impression_Goal__c = 2,
            Audience_Targeting__c = '1P ACR',
            Device_Type__c = 'CTV',
            Placement_Billing_Name__c = 'test Placement',
            Placement_Category__c = 'Added Value',
            Placement_Type__c = 'ROS',
      		Product_Full_Name__c = 'test Placement',
            End_Date__c = system.now(),
            Product_Family__c = 'Managed Service Impressions',
            OpportunityId = opp.Id,
            Flight_Start_Date__c = flightStartDate,
            Flight_End_Date__c = flightEndDate,
            MinImpressions__c = MinImpressions,
            CPM__c = CPM,
        BETA_Program__c = 'Collections Beta',
            IO_Product_Display_Name__c = 'test',
        	Audience_Segment_Details__c = 'Test Audience_Segment_Details__c',
            Country__c = 'India'
        );
        insert oliCTVNative1;

    List<Opportunity_Seller__c> osList = [
      SELECT id, Seller__c, Opportunity__c, Percentage__c
      FROM Opportunity_Seller__c
      WHERE Opportunity__c = :opp.Id
    ];

    List<Opportunity_Product_Seller__c> opsList = [
      SELECT id, Seller__c, Opportunity_Product__c
      FROM Opportunity_Product_Seller__c
      WHERE Opportunity_Product__c = :oliCTVNative1.Id
    ];

    System.assert(
      opsList.size() == 1,
      'One Opportunity Product Seller should be added'
    );
    System.assert(osList.size() == 1, 'One Opportunity Seller should be added');

    Opportunity_Seller__c os = osList[0];
    os.Percentage__c = 80;
    update os;

    opsList = [
      SELECT id, Seller__c, Opportunity_Product__c, Seller_Percentage__c
      FROM Opportunity_Product_Seller__c
      WHERE Opportunity_Product__c = :oliCTVNative1.Id
    ];

    System.assert(
      opsList[0].Seller_Percentage__c == 80,
      'Seller Percentage should be updated'
    );

    //delete os;
    opsList = [
      SELECT id, Seller__c, Opportunity_Product__c, Seller_Percentage__c
      FROM Opportunity_Product_Seller__c
      WHERE Opportunity_Product__c = :oliCTVNative1.Id
    ];

  /*  System.assert(
      opsList.size() == 0,
      'Opportunity Product Seller should be deleted'
    );*/

    Test.StopTest();
  }
}