force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Direct__c.field-meta.xml
<CustomField>
    <fullName>Client_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Default_Billing_Ad_Server__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Ad_Server__c</fullName>
    <label>Default Billing Ad Server</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Party</fullName>
                <default>true</default>
                <label>1st Party</label>
            </value>
            <value>
                <fullName>Adform</fullName>
            </value>
            <value>
                <fullName>Brightroll</fullName>
            </value>
            <value>
                <fullName>Comscore</fullName>
            </value>
            <value>
                <fullName>DFA/DCM</fullName>
            </value>
            <value>
                <fullName>DV</fullName>
            </value>
            <value>
                <fullName>ExtremeReach</fullName>
            </value>
            <value>
                <fullName>Flashtalking</fullName>
            </value>
            <value>
                <fullName>IAS</fullName>
            </value>
            <value>
                <fullName>Innovid</fullName>
            </value>
            <value>
                <fullName>MOAT</fullName>
            </value>
            <value>
                <fullName>Sizmek</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Point_Of_Contact_Primary__c.field-meta.xml
<CustomField>
    <fullName>Main_Point_Of_Contact_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Point Of Contact (Primary)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Main Point Of Contact (Primary))</relationshipLabel>
    <relationshipName>Opportunities_MainPOC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityStageChangeTriggerTest.cls
@isTest(isParallel=false)
public class OpportunityStageChangeTriggerTest {
  @isTest
  static void resellerAccountTest() {
    TestHelper.setupTests();
    Test.startTest();

    Boolean exceptionThrown = false;

    Account acc1 = new Account(
      Name = 'Test Account 1',
      Type = Constants.ACCOUNT_TYPE_RESELLER
    );
     
    Account acc2 = new Account(
      Name = 'Test Account 2',
      Type = Constants.ACCOUNT_TYPE_AGENCY
    );
      
    insert new List<Account>{ acc1, acc2 };
        
    acc2.Account_Review_Status__c  = 'Approved';
    update acc2;
      
    acc1.Account_Review_Status__c  = 'Approved';
    update acc1;

    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);
    Date bookingDate = Date.newInstance(2021, 3, 12);

    Contact contact1 = new Contact(
      LastName = 'Account Contact',
      AccountId = acc1.Id,
      Email = 'test1234@gmail.com'
    );
    insert contact1;

    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = flightEndDate,
      Campaign_Name__c = 'test',
      StageName = 'RFP received',
      Flight_Start_Date__c = flightStartDate,
      Flight_End_Date__c = flightEndDate,
      AccountId = acc1.Id,
      Seller_Region__c = Constants.BUSINESS_VERTICAL_RESELLER,
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      //IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Client_Direct__c = true,
      Market_Type__c = 'M&E'
    );

    try {
      opp.Seller_Region__c = Constants.BUSINESS_VERTICAL_NATIONAL_ME;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
      /*System.assert(
        e.getMessage().contains('Please select business vertical as Reseller')
      );*/
    } finally {
      opp.Seller_Region__c = Constants.BUSINESS_VERTICAL_RESELLER;
     // System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      opp.Seller_Region__c = Constants.BUSINESS_VERTICAL_RESELLER;
      opp.AccountId = acc2.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
      
    } finally {
      opp.AccountId = acc1.id;
      System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.Seller_Region__c = Constants.BUSINESS_VERTICAL_NATIONAL_ME;
      opp.AccountId = acc2.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
     
    }

    try {
      exceptionThrown = false;
      opp.Seller_Region__c = Constants.BUSINESS_VERTICAL_RESELLER;
      opp.AccountId = acc1.id;
      System.debug('Inserting opp' + opp.id + ' ' + opp.AccountId);
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Exception thrown ' + e.getMessage());
      System.debug('Opp ' + opp.Account.Name);
    } finally {
      /*System.assertEquals(
        true,
        exceptionThrown,
        'Exception should not be thrown'
      );*/
    }

    Test.StopTest();
  }

  @isTest
  static void recordTypeMismatchTest() {
    TestHelper.setupTests();
    Test.startTest();

    Boolean exceptionThrown = false;

    Account acc = new Account(
      Name = 'Test Account',
      Type = Constants.ACCOUNT_TYPE_AGENCY
    );
    insert acc;
	acc.Account_Review_Status__c='Approved';
    update acc;
    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = Date.newInstance(2022, 3, 30),
      StageName = 'RFP received',
      Campaign_Name__c = 'test',
      AccountId = acc.Id,
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      //IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E'
    );

    Pricebook2 managedPB = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      IsActive = true
    );
    Pricebook2 selfPB = new Pricebook2(
      Name = Constants.PRICEBOOK_SELF,
      IsActive = true
    );
    Pricebook2 insightsPB = new Pricebook2(
      Name = Constants.PRICEBOOK_CORPORATE,
      IsActive = true
    );
    insert new List<Pricebook2>{ managedPB, selfPB, insightsPB };

    RecordType managedRT = [
      SELECT id, name
      FROM RecordType
      WHERE name = :Constants.RECORD_TYPE_MANAGED
    ];
    

    // Tests using today as CreatedDate
    try {
     
      opp.Pricebook2Id = selfPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
     
    } finally {
     // System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.Pricebook2Id = managedPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
      
    } finally {
      
    }

    try {
      exceptionThrown = false;
      opp.Pricebook2Id = insightsPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
     
    } finally {
      System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.RecordTypeId = managedRT.id;
      opp.Pricebook2Id = insightsPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
      
    } finally {
      //System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      
      opp.Pricebook2Id = selfPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
      
    } finally {
      //System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      
      opp.Pricebook2Id = managedPB.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
     
    } finally {
     // System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.RecordTypeId = managedRT.id;
      insert opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
      
     
      
    }

    try {
      exceptionThrown = false;
      opp.RecordTypeId = managedRT.id;
      opp.Pricebook2Id = managedPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
      
    }

    try {
      exceptionThrown = false;
      opp.Pricebook2Id = selfPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
      
    }

    try {
      exceptionThrown = false;
      
      opp.Pricebook2Id = insightsPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
      
    }

    Test.StopTest();
  }

  @isTest
  static void recordTypeMismatchTestOlderOpp() {
    TestHelper.setupTests();
    Account acc = new Account(
      Name = 'Test Account',
      Type = Constants.ACCOUNT_TYPE_AGENCY
    );
    insert acc;
    acc.Account_Review_Status__c='Approved';
    update acc;

    Pricebook2 managedPB = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      IsActive = true
    );
    Pricebook2 selfPB = new Pricebook2(
      Name = Constants.PRICEBOOK_SELF,
      IsActive = true
    );
    Pricebook2 insightsPB = new Pricebook2(
      Name = Constants.PRICEBOOK_CORPORATE,
      IsActive = true
    );
    insert new List<Pricebook2>{ managedPB, selfPB, insightsPB };

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = Date.newInstance(2022, 3, 30),
      StageName = 'RFP received',
      Campaign_Name__c = 'test',
      AccountId = acc.Id,
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      //IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E',
      Client_Direct__c = true,
      Flight_Start_Date__c = system.today(),
      Flight_End_Date__c = system.today()
    );
    insert opp;

    Test.setCreatedDate(opp.Id, Constants.OPP_TYPE_MISMATCH_DATE.addDays(-1));
    Test.startTest();

    Boolean exceptionThrown = false;

    RecordType managedRT = [
      SELECT id, name
      FROM RecordType
      WHERE name = :Constants.RECORD_TYPE_MANAGED
    ];
    
    // Tests using older CreatedDate
    try {
      exceptionThrown = false;
      opp.RecordTypeId = managedRT.id;
      opp.Pricebook2Id = selfPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );
    }

    try {
      exceptionThrown = false;
      opp.Pricebook2Id = managedPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );
    }

    try {
      exceptionThrown = false;
      
      opp.Pricebook2Id = selfPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      /*System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );*/
    }

    try {
      exceptionThrown = false;
      
      opp.Pricebook2Id = managedPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      /*System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );*/
    }

    try {
      exceptionThrown = false;
      opp.RecordTypeId = managedRT.id;
      opp.Pricebook2Id = insightsPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      /*System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );*/
    }

    try {
      exceptionThrown = false;
      opp.Pricebook2Id = insightsPB.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Error ' + e.getMessage());
    } finally {
      /*System.assertEquals(
        false,
        exceptionThrown,
        'No exception should be thrown for older created date'
      );*/
    }

    Test.StopTest();
  }

  @isTest
  static void opportunityClosedWonTest() {
    TestHelper.setupTests();
    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);
    Id pricebookId = Test.getStandardPricebookId();

    Account acc = new Account(
      Name = 'Test Account',
      Type = Constants.ACCOUNT_TYPE_AGENCY
    );
    insert acc;
	acc.Account_Review_Status__c='Approved';
    update acc;
    Contact contact1 = new Contact(
      LastName = 'Account Contact',
      AccountId = acc.Id,
      Email = 'test234@gmail.com'
    );
    insert contact1;

    Product2 productNative = new Product2(
      Name = 'CTV native',
      ProductCode = 'Code',
      isActive = true,
      CanUseRevenueSchedule = true
    );
    insert productNative;

    Pricebook2 managedPB = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      IsActive = true
    );

    insert new List<Pricebook2>{ managedPB };

    PricebookEntry pbEntryNative = new PricebookEntry(
      Pricebook2Id = managedPB.id,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );
    PricebookEntry pbEntryNativeStandard = new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = productNative.Id,
      UnitPrice = 1200.00,
      IsActive = true
    );

    insert new List<PricebookEntry>{ pbEntryNativeStandard, pbEntryNative };

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = Date.newInstance(2022, 3, 30),
      StageName = 'RFP received',
      AccountId = acc.Id,
      Campaign_Name__c = 'test',
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
	  Primary_billing_contact__c = contact1.Id,
      //IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E',
      Client_Direct__c = true,
      Flight_Start_Date__c = system.today(),
      Flight_End_Date__c = system.today()
    );
    insert opp;

    OpportunityLineItem oliCTVNative = new OpportunityLineItem(
      PricebookEntryId = pbEntryNative.id,
      UnitPrice = 1000,
      OpportunityId = opp.Id,
      Flight_Start_Date__c = flightStartDate,
      Flight_End_Date__c = flightEndDate,
      MinImpressions__c = 100000,
      CPM__c = 20,
      Country__c = Constants.COUNTRY_US
    );

    Test.startTest();

    Boolean exceptionThrown = false;

    try {
      exceptionThrown = false;
      opp.StageName = Constants.STAGE_CLOSED_WON;
      opp.Default_Billing_Ad_Server__c = 'Adform';
      opp.Country__c = 'India';
      opp.Main_Point_Of_Contact_Primary__c = contact1.id;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      System.debug('Exception ' + e.getMessage());
     
    } finally {
      System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.StageName = 'Dummy';
      update opp;  
      opp.StageName = Constants.STAGE_WAITING_ASSETS;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
      
    } finally {
      //System.assertEquals(true, exceptionThrown, 'No exception was thrown');
    }

    try {
      exceptionThrown = false;
      opp.StageName = Constants.STAGE_CLOSED_WON;
      insert oliCTVNative;
      update opp;
    } catch (Exception e) {
      exceptionThrown = true;
    } finally {
      
    }

    Test.StopTest();
  }
}