force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Direct__c.field-meta.xml
<CustomField>
    <fullName>Client_Direct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_End_Date__c</fullName>
    <label>Flight End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flight_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Flight_Start_Date__c</fullName>
    <label>Flight Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Seller__c/Opportunity_Seller__c.object-meta.xml
<CustomObject>
    <label>Opportunity Seller</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Opportunity Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Sellers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Seller__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Sellers</relationshipLabel>
    <relationshipName>Opportunity_Sellers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityAfterInsertTriggerTest.cls
@isTest
public class OpportunityAfterInsertTriggerTest {
  @isTest
  static void opportunityUpdateTest() {
    Test.startTest();

    Boolean exceptionThrown = false;

    Account acc = new Account(Name = 'Test Account');
    insert acc;
    acc.Account_Review_Status__c='Approved';
    update acc;

    Date flightStartDate = Date.newInstance(2021, 5, 12);
    Date flightEndDate = Date.newInstance(2021, 8, 20);
    Date bookingDate = Date.newInstance(2021, 3, 12);

    Contact contact1 = new Contact(
      LastName = 'Account Contact',
      AccountId = acc.Id,
      Email = 'test@lgads.tv'
    );
    insert contact1;

    Pricebook2 pb = new Pricebook2(
      Name = Constants.PRICEBOOK_MANAGED,
      isActive = true
    );
    insert pb;

    Opportunity opp = new Opportunity(
      Name = 'Test Opportunity',
      CloseDate = bookingDate,
      StageName = 'RFP received',
      Flight_Start_Date__c = flightStartDate,
      Flight_End_Date__c = flightEndDate,
      AccountId = acc.Id,
      Seller_Region__c = 'National Media & Entertainment',
      Brand_Name__c = 'Test',
      Brand_Id__c = '1111',
      IO_Number_Available__c = 'Not Available',
      CSM__c = UserInfo.getUserId(),
      Market_Type__c = 'M&E',
	  Client_Direct__c=TRUE,
      Campaign_Name__c = 'test'
    );
    insert opp;
    Opportunity updatedOpp = [
      SELECT id, OwnerId
      FROM Opportunity
      WHERE id = :opp.Id
    ];

    List<Opportunity_Seller__c> osList = [
      SELECT id, Opportunity__c, Seller__c, Percentage__c
      FROM Opportunity_Seller__c
      WHERE Opportunity__c = :opp.Id
    ];
    System.assert(
      osList.size() == 1,
      'Number of Opportunity Sellers do not match'
    );
    System.assert(
      osList[0].Seller__c == updatedOpp.OwnerId,
      'Default Seller does not match'
    );
    System.assert(
      osList[0].Percentage__c == 100,
      'Default Percentage should be 100'
    );

    Test.StopTest();
  }
}