force-app/main/default/objects/Account/fields/Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Review_Status__c</fullName>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
                <default>true</default>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <inlineHelpText>Copy from Insights</inlineHelpText>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency</label>
</RecordType>

force-app/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <label>Agency</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Agency__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertisers</relationshipLabel>
    <relationshipName>Agencies_Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Contact?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <inlineHelpText>This value gets appended to the end of the opportunity name</inlineHelpText>
    <label>Campaign Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IO_Number_Available__c.field-meta.xml
<CustomField>
    <fullName>IO_Number_Available__c</fullName>
    <inlineHelpText>Select if IO Number is available from the client</inlineHelpText>
    <label>IO Number Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Point_Of_Contact_Primary__c.field-meta.xml
<CustomField>
    <fullName>Main_Point_Of_Contact_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Point Of Contact (Primary)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Main Point Of Contact (Primary))</relationshipLabel>
    <relationshipName>Opportunities_MainPOC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Billing_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Secondary Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Secondary Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseBeforeUpdateTest.cls
@isTest
public class CaseBeforeUpdateTest {

    private class RestMock implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      String fullJson = '{"data":{"permalink_url":"https://app.asana.com/0/1200134875094939/1200334050604084"}}';

      HTTPResponse res = new HTTPResponse();
      res.setHeader('Content-Type', 'text/json');
      res.setBody(fullJson);
      res.setStatusCode(200);
      return res;
    }
  }
    
    @isTest
    static void testNoFileUploadedError() {
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
        //RecordType rtype = [SELECT Id, DeveloperName from RecordType where DeveloperName = 'RFI' and SobjectType = 'Case' LIMIT 1];
        Id rTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RFP').getRecordTypeId();
        
        Account acc = new Account(name='test acc',Account_Review_Status__c = 'In Review');
		insert acc;
        Account acc4 = new account(id = acc.Id, Account_Review_Status__c = 'Approved');
        update acc4;
		Account acc2 = new Account(name='agency acc');
		acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency').getRecordTypeId();
		insert acc2;
        Account acc3 = new account(id = acc2.Id, Account_Review_Status__c = 'Approved');
        update acc3;
		Contact contact1 = new Contact(FirstName='Ricky', LastName='Pointing');
		contact1.AccountId = acc4.Id;
		contact1.Is_Billing_Contact__c = TRUE;
		contact1.Email = 'test.user1@example.com';
		insert contact1;
		Contact contact2 = new Contact(FirstName='Bark', LastName='Putin');
		contact2.Email = 'test.user2@example.com';
		contact2.AccountId = acc.Id;
		insert contact2;
		Contact contact3 = new Contact(FirstName='Test', LastName='Data');
		contact3.Email = 'test.user3@example.com';
		contact3.AccountId = acc.Id;
		insert contact3;
		Opportunity opp = new Opportunity(Name='test opp',Primary_Billing_Contact__c=contact1.Id,Secondary_Billing_Contact__c=contact2.Id, Amount=100, TotalOpportunityQuantity=10, StageName='Prospecting', CloseDate=System.today(), AccountId=acc.Id);
		opp.Seller_Region__c = 'National Media & Entertainment';
		opp.Brand_Name__c = 'Test';
		opp.Brand_Id__c = '1111';
		opp.IO_Number_Available__c = 'Not Available';
		opp.CSM__c = UserInfo.getUserId();
		opp.Market_Type__c = 'M&E';
		opp.Main_Point_Of_Contact_Primary__c = contact3.Id;
		opp.Agency__c = acc3.Id;
		opp.Campaign_Name__c = 'test camp';
		insert opp;

        // Create test case
        Case c = new Case(
            RecordTypeId = rTypeId,
            Status = 'New',
            Subject = 'Test Subject',
            Opportunity__c = opp.Id,
            Media_Plan_AM__c = true
        );
        insert c;
        
        // Assert created case details
        System.assertEquals(rTypeId, c.RecordTypeId);
        System.assertEquals('New', c.Status);
        
        // Update case status
        c.Status = 'In Progress';
        try {
            // Update case
            update c;
            //System.fail('Expected validation error but none was thrown');
        } catch (Exception e) {
            // Assert expected error message or type
            System.assertEquals(true, e.getMessage().contains('You must upload at least'));
        }
        
        Test.stopTest();
    }
}