force-app/main/default/objects/Opportunity/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <description>Has validation rule based on the picklist values.</description>
    <inlineHelpText>M&amp;E - Media and Entertainment
GM - General Market</inlineHelpText>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>M&amp;E</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seller_Region__c.field-meta.xml
<CustomField>
    <fullName>Seller_Region__c</fullName>
    <label>Business Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>General Market East</fullName>
            </value>
            <value>
                <fullName>General Market West</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>National Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseListByFieldSetCtrlTest.cls
@isTest(SeeAllData=true)
private class CaseListByFieldSetCtrlTest {

    private class RestMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
          String fullJson = '{"data":{"permalink_url":"https://app.asana.com/0/1200134875094939/1200334050604084"}}';
    
          HTTPResponse res = new HTTPResponse();
          res.setHeader('Content-Type', 'text/json');
          res.setBody(fullJson);
          res.setStatusCode(200);
          return res;
        }
      }

    @isTest
    static void testFetchCaseFieldSetData() {
        // Create a test opportunity
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Opportunity testOpp = [Select id from Opportunity Limit 1];//new Opportunity(Name = 'Test Opportunity', StageName = 'Prospecting',CloseDate=System.TODAY(), Seller_Region__c='General Market East', Market_Type__c='GM');

        // Create test cases related to the opportunity
        Case testCase1 = new Case(Subject = 'Test Case 1', Opportunity__c = testOpp.Id);
        Case testCase2 = new Case(Subject = 'Test Case 2', Opportunity__c = testOpp.Id);
        insert new List<Case>{testCase1, testCase2};

        // Call the fetchCaseFieldSetData method
        List<Case> resultCases = CaseListByFieldSetCtrl.fetchCaseFieldSetData(testOpp.Id);

        //Assert that the result contains the expected cases
        System.assertEquals(2, resultCases.size(), 'The number of cases returned should be 2');
    }

    @isTest
    static void testGetFieldSet() {
        // Call the getFieldSet method with valid parameters
        String result = CaseListByFieldSetCtrl.getFieldSet('Case', 'CaseListlwcFieldSet');

        // Assert that the result is not empty
        System.assertNotEquals('', result, 'The result should not be empty');
    }

    @isTest
    static void testGetFieldSetWithInvalidParameters() {
        // Call the getFieldSet method with invalid parameters
        String result = CaseListByFieldSetCtrl.getFieldSet('InvalidObject', 'InvalidFieldSet');
    }
}