force-app/main/default/objects/Common_Bill__c/Common_Bill__c.object-meta.xml
<CustomObject>
    <label>Total Bill</label>
    <nameField>
        <label>Bill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Total Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Common_Bill__c/fields/LG_Sales_PMP__c.field-meta.xml
<CustomField>
    <fullName>LG_Sales_PMP__c</fullName>
    <label>LG Sales PMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Common_Bill__c/fields/Platform_PMP__c.field-meta.xml
<CustomField>
    <fullName>Platform_PMP__c</fullName>
    <label>Platform PMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Common_Bill__c/fields/Programmatic_Others__c.field-meta.xml
<CustomField>
    <fullName>Programmatic_Others__c</fullName>
    <label>Programmatic Others</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PMP_Estimation__c/PMP_Estimation__c.object-meta.xml
<CustomObject>
    <label>PMP Estimation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>PMP Estimation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMP Estimations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMP_Estimation__c/fields/Partner_PMP__c.field-meta.xml
<CustomField>
    <fullName>Partner_PMP__c</fullName>
    <label>Partner PMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PMP_Estimation__c/fields/Sales_PMP__c.field-meta.xml
<CustomField>
    <fullName>Sales_PMP__c</fullName>
    <label>Sales PMP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TotalBillsFieldsUpdateTriggerTest.cls
@isTest
public class TotalBillsFieldsUpdateTriggerTest {
    @isTest
  public static void TotalBillsFieldsUpdateTriggertestmethod() {
    Test.startTest();
    Date startDate = Date.today().addDays(-1);
    Date endDate = Date.today().addDays(6);

    Product2 productSocial = new Product2(
      Name = 'Social',
      ProductCode = 'Code',
      isActive = true,
      CanUseRevenueSchedule = true
    );
    insert productSocial;

    PMPEstimationController.createEntries(startDate, endDate);
    List<Common_Bill__c> bills = new List<Common_Bill__c>();

    // Create actual bills upto start date
    for (Date d = startDate.addDays(-8); d <= startDate; d = d.addDays(1)) {
      Common_Bill__c bill = new Common_Bill__c(
        Date__c = d,
        Partner_PMP__c = 200,
        Platform_PMP__c = 200,
        LG_Sales_PMP__c = 200,
        Programmatic_Others__c = 200
      );
      bills.add(bill);
    }
    insert bills;
    PMPEstimationController.updateEntries(startDate, endDate);
    List<PMP_Estimation__c> ests = [
      SELECT
        id,
        date__c,
        Partner_pmp__c,
        Platform_pmp__c,
        sales_pmp__c,
        Programmatic_Others__c
      FROM PMP_Estimation__c
      WHERE Date__c >= :startDate AND Date__c <= :endDate
      ORDER BY Date__c ASC
    ];

    for (Integer i = 0; i < ests.size(); i++) {
      System.assert(
        ests[i].Partner_PMP__c == 200,
        'Partner PMP value is incorrect for ' + ests[i].Date__c
      );
      System.assert(
        ests[i].Platform_PMP__c == 200,
        'Platform PMP value is incorrect for ' + ests[i].Date__c
      );
      System.assert(
        ests[i].Sales_PMP__c == 200,
        'Sales PMP value is incorrect for ' + ests[i].Date__c
      );
      System.assert(
        ests[i].Programmatic_Others__c == 200,
        'Sales PMP value is incorrect for ' + ests[i].Date__c
      );
    }

    Test.stopTest();
  }
   
}